services:
  backend:
    build: ./backend
    container_name: django_backend
    command: gunicorn weather_station.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    expose:
      - 80

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  proxy:
    build: ./proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/certbot:/var/lib/certbot:ro
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume: