# Generated by Django 5.2 on 2025-07-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
