# Generated by Django 5.2 on 2025-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0002_weatherdataentry_delete_weatherdata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdataentry',
            options={'ordering': ['-timestamp']},
        ),
    ]
