# Generated by Django 5.2 on 2025-07-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0003_alter_weatherdataentry_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weatherdataentry',
            index=models.Index(fields=['timestamp'], name='weather_dat_timesta_92f10f_idx'),
        ),
    ]
