# Generated by Django 5.2 on 2025-08-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0006_weatherstationapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherstationapikey',
            options={'ordering': ('-created',), 'verbose_name': 'Weather Station API Key', 'verbose_name_plural': 'Weather Station API Keys'},
        ),
    ]
