# Generated by Django 5.2 on 2025-08-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0004_weatherdataentry_weather_dat_timesta_92f10f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_tips', models.PositiveIntegerField()),
                ('rainfall_mm', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rainfall_calibration_factor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherDataEntry',
        ),
        migrations.AddField(
            model_name='reading',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weather_data_handler.uploadbatch'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='weather_data_handler.weatherstation'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['timestamp'], name='weather_dat_timesta_1853db_idx'),
        ),
    ]
