# Generated by Django 5.2 on 2025-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data_handler', '0007_alter_weatherstationapikey_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
