# Generated by Django 6.0.7 on 2026-07-31 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('822ae70d-b09c-4ab6-a4c4-4dfe6fc06a79'), editable=False, primary_key=True, serialize=False)),
                ('registration_secret_hash', models.CharField(max_length=128)),
                ('api_key_prefix', models.CharField(max_length=8, unique=True)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('pairing_code', models.CharField(max_length=8, null=True, unique=True)),
                ('pairing_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='PENDING', max_length=10)),
                ('firmware_version', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weatherstation.device')),
            ],
        ),
    ]
