# Generated by Django 6.0.7 on 2026-07-31 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.UUID('096d66b3-2fcc-413c-9b47-61e732f63195'), editable=False, primary_key=True, serialize=False),
        ),
    ]
