# Generated by Django 6.0.7 on 2026-09-09 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstation', '0003_weatherstation_user_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='api_key_prefix',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='INACTIVE', max_length=10),
        ),
    ]
