name: Deploy to production server

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.DOT_ENV }}" > .env
        
      - name: Pull latest Docker images
        run: docker compose pull

      - name: Build and Deploy
        run: docker compose up -d --build --force-recreate

      - name: Run Django Migrations
        run: docker compose run --rm backend python manage.py migrate --noinput
        
      - name: Prune old Docker images
        run: docker image prune -f
